name: Hello World Workflow

on:
  push:
  workflow_dispatch:


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run:
          echo "Hello, world 123!"
          # print precise time, scale to second
          echo "The time is $(date +%s)."
          sleep 3
          echo "The time is $(date +%s)."
