name: Hello World Workflow

on:
  push:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, world 123!"
      - name: Step 2
#        echo issue comment
        run: echo ${{ github.event.comment.body }}
