name: Issue Listener

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo issue comment
        run:
          echo ${{ github.event.comment.body }}
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'I like pizza'}}
    steps:
      - name: Call workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: hello_world.yml

