name: Issue Listener

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo issue comment
        run:
          echo ${{ github.event.comment.body }}



