name: Issue Listener

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo issue comment
        run:
          echo ${{ github.event.comment.body }}
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'I like pizza'}}
    steps:
      - name: Like pizza
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });


